//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SoftList
    {
        public int SoftID { get; set; }
        public string SoftName { get; set; }
        public string SoftIntro { get; set; }
        public string SoftType { get; set; }
        public string Contest { get; set; }
        public string DownLink { get; set; }
    }
}
