//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursePlatformEntities1 : DbContext
    {
        public CoursePlatformEntities1()
            : base("name=CoursePlatformEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tb_ApplySoftList> Tb_ApplySoftList { get; set; }
        public DbSet<Tb_ApplyTable> Tb_ApplyTable { get; set; }
        public DbSet<Tb_City> Tb_City { get; set; }
        public DbSet<Tb_CourseBaseInform> Tb_CourseBaseInform { get; set; }
        public DbSet<Tb_FieldTable> Tb_FieldTable { get; set; }
        public DbSet<Tb_ManageUser> Tb_ManageUser { get; set; }
        public DbSet<Tb_Resource> Tb_Resource { get; set; }
        public DbSet<Tb_ResourceType> Tb_ResourceType { get; set; }
        public DbSet<Tb_SoftCourse> Tb_SoftCourse { get; set; }
        public DbSet<Tb_SoftList> Tb_SoftList { get; set; }
        public DbSet<Tb_SoftUser> Tb_SoftUser { get; set; }
        public DbSet<Tb_StuUser> Tb_StuUser { get; set; }
    }
}
