//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ApplyTable
    {
        public int ApplyID { get; set; }
        public string UnitNameCH { get; set; }
        public string UnitNameEN { get; set; }
        public string ChargePerson { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string UnitAddress { get; set; }
        public string ZipCode { get; set; }
        public string UnitIntro { get; set; }
        public string TeacherNum { get; set; }
        public string StuNum { get; set; }
        public string Gradu2015Num { get; set; }
        public string SeniorTitleNum { get; set; }
        public string IntermediateTitleNum { get; set; }
        public string OtherTitleNum { get; set; }
        public string TechTeacherNum { get; set; }
        public string AuthTechTeacherNum { get; set; }
        public string EngineRoomArea { get; set; }
        public string ComputerNumConfig { get; set; }
        public System.DateTime RecordTime { get; set; }
        public int UserID { get; set; }
        public int IsPass { get; set; }
        public string input1 { get; set; }
        public string input2 { get; set; }
        public string input3 { get; set; }
        public string input4 { get; set; }
        public string input5 { get; set; }
        public string input6 { get; set; }
        public string input7 { get; set; }
        public string input8 { get; set; }
        public string input9 { get; set; }
        public string input10 { get; set; }
        public string input11 { get; set; }
        public string input12 { get; set; }
        public string input13 { get; set; }
        public string input14 { get; set; }
        public string input15 { get; set; }
        public string input16 { get; set; }
        public string input17 { get; set; }
        public string input18 { get; set; }
        public string input19 { get; set; }
        public string input20 { get; set; }
        public string input21 { get; set; }
        public string input22 { get; set; }
        public string input23 { get; set; }
        public string input24 { get; set; }
        public string input25 { get; set; }
        public string input26 { get; set; }
        public string input27 { get; set; }
        public string input28 { get; set; }
        public string input29 { get; set; }
        public string input30 { get; set; }
        public string input31 { get; set; }
    }
}
