//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ApplySoftList
    {
        public int ApplySoftID { get; set; }
        public string SoftCourseName { get; set; }
        public Nullable<int> TrainNumPerYear { get; set; }
        public Nullable<int> ApplyNum { get; set; }
        public Nullable<int> ApplyID { get; set; }
        public Nullable<int> SoftID { get; set; }
    }
}
