//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Resource
    {
        public int ResourceID { get; set; }
        public string ResourceName { get; set; }
        public int ResourceTypeID { get; set; }
        public string ResourcePath { get; set; }
        public bool IsConvertFinish { get; set; }
        public string PDFPath { get; set; }
        public string swfPath { get; set; }
        public System.Guid UpUserID { get; set; }
        public string UserType { get; set; }
        public System.DateTime RecordTime { get; set; }
    }
}
