//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_StuUser
    {
        public System.Guid StuID { get; set; }
        public string StuName { get; set; }
        public Nullable<int> StuAge { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public Nullable<int> CityID { get; set; }
        public string DetailAddress { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string IDCard { get; set; }
        public string CompanyName { get; set; }
        public string PostCode { get; set; }
        public System.DateTime RecordTime { get; set; }
        public string ClassName { get; set; }
        public string SchoolName { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> ProvinceID { get; set; }
    }
}
